### ISSUE TITLE
Add more wording for execute JavaScript command.

### ISSUE THREAD

**Issue by Natrium729** [vorple/inform7#17]
I think a `the` should be allowed after `execute`. Also, maybe allow `JS` in place of `JavaScript`:

```
To execute the/-- JavaScript/JS command/code:
```

You could even allow `JS` instead of `JavaScript` in other phrases, such as `the text returned by the JS command`.

**Comment by Natrium729** [comment]
Also, the `the` in `value returned by the JavaScript command` and the like should maybe be optional.

**Comment by juhana** [comment]
Agreed on the "the"s which should be available and optional, but I'm a bit reluctant to add abbreviations which would go against the I7 Standard Library style.

If you end up needing lots of JavaScript commands in a project, you can create a shorthand for yourself:

```
To JS (code - text):
  execute JavaScript command code.
```

**Comment by Natrium729** [comment]
I wasn't sure too, that why I wrote "maybe"! However, since "JS" is quite a standard abbreviation for "JavaScript", it may be worth thinking about it.

But then, as you wrote, I could just add my own phrase, so it's not a big deal.
