### ISSUE TITLE
In JS commands, text substitutions after a period may cause unwanted linebreaks

### ISSUE THREAD

**Issue by Natrium729** [vorple/inform7#19]
If you have a `to say` phrase that outputs some JavaScript identifier, you can't use it after a period (e.g. to retrieve a key from an object) because Inform automatically adds linebreaks after periods.

```inform7
To say my JS identifier:
    say "myId".

[This will fail.]
execute JavaScript command "myObject.[my JS identifier];".
```

It can be solved by adding `-- running on` after the `to say` phrase:

```inform7
To say my JS identifier -- running on:
    say "myId".
```

I don't think it can be solved on Vorple's side, but maybe a line in the documentation about this issue should be added? Because it took me a lot of time to find why my code wasn't working.

And if ever there are some text substitutions of this kind in Vorple extensions, we should be sure to mark them as running on.

**Comment by juhana** [comment]
This is true, although thankfully it happens only with say phrases that contain punctuation. The web site documentation will contain discussion about the topic when the next version is released.
