### ISSUE TITLE
error playing sound, "o.on is not a function."

### ISSUE THREAD

**Issue by wysiwyggins** [vorple/inform7#22]
When executing the "play sound effect file 'foo.mp3'" action, this error appears in the interpreter browser window:

`JavaScript code from story file threw an error: o.on is not a function. (In 'o.on("ended",function(){this.remove()})', 'o.on' is undefined) vorple.audio.playSound("audio/foo.mp3", {looping: false})`

The inspector console shows the same error, and also:

`[Error] Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.`

**Comment by juhana** [comment]
This should be fixed in the latest version (3.2.0).
