### ISSUE TITLE
interpreter folder missing css & js files

### ISSUE THREAD

**Issue by Tofutush** [vorple/inform7#26]
this may be stupid, but i have downloaded Vorple for Inform 7, and when i tried to test it on the Onyx sample project, this is what shows up in the console.

![image](https://github.com/vorple/inform7/assets/63438312/8a55f44e-e36f-4c19-b037-6b27e48738ad)

it seems that the “interpreter” folder is missing a bunch of css and js files. the folder only contains the “Onyx.gblorb.js” file. and it seems that Vorple uses jQuery, but that file is missing too, hence the “$ is not defined” message?

i just did this today so the version is probably correct. does anyone know why these files are missing and how this issue may be fixed?

**Comment by juhana** [comment]
All the necessary files are included in the download (including the ones mentioned in the error message) so all I can advise is to review the installation instructions and make sure that everything is in the correct place. If nothing else works, let me know your Inform version and operating system and I'll take a closer look.

**Comment by Tofutush** [comment]
ah, thank you! turns out i downloaded the github code zip (like, *this thing* right here) instead of the one on vorple-if.com you were supposed to download. but to be honest the documentation was a bit misleading, as the link in "setting up a local server" lead here...

![image](https://github.com/vorple/inform7/assets/63438312/d52cc345-726f-4cc5-8dc4-a2fb8b8eaf31)

and the link in "installing Vorple for Inform 7" leads to a 404 (having written "download" instead of "download.html"

![image](https://github.com/vorple/inform7/assets/63438312/6f2c340b-cfeb-45fe-8177-4e2210e990dd)

so this may be a small error here.

**Comment by juhana** [comment]
The instructions are indeed wrong, I'll fix that. Thanks!
