### ISSUE TITLE
Command history manipulated in the wrong order

### ISSUE THREAD

**Issue by hlabrand** [vorple/inform7#7]
From what I can see by testing the I6 libraries, the JS "haven.prompt.history.remove()" removes the first command that was typed, not the last!
The same goes with "haven.prompt.history.add('cmd')", this command appears last in the command history (as if it had been the first one to be typed)

**Comment by juhana** [comment]
The array that holds the command history in Haven was reversed for easier manipulation by the interpreter, but because it was the "wrong way around" it would easily lead to logical errors like this. It's now right way around in the interpreter, and no changes to Inform libraries is needed.
